apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: html-db-deployment
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: html-db
    template:
      metadata:
        labels:
          app: html-db
      spec:
        containers:
        - name: html-db
          image: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/html-db-app:latest
          ports:
          - containerPort: 8080
