apiVersion: v1
  kind: Service
  metadata:
    name: html-db-service
  spec:
    selector:
      app: html-db
    ports:
      - protocol: TCP
        port: 80
        targetPort: 8080
    type: LoadBalancer
