name: Build and Deploy to EKS

on:
  push:
    branches: ["master"]

jobs:
  build-and-deploy:
  runs-on: self-hosted

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build WAR File
      run: mvn clean package -DskipTests

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build & Push Docker Image
      run: |
        docker build -t mywebapp .
        docker tag mywebapp:latest ${{ secrets.ECR_URI }}:latest
        docker push ${{ secrets.ECR_URI }}:latest

    - name: Update kubeconfig for EKS
      run: |
        aws eks update-kubeconfig --name java-cluster --region ap-south-1
        kubectl get nodes

    - name: Deploy to EKS
      run: |
        kubectl apply -f k8s/deployment.yaml --validate=false
        kubectl apply -f k8s/service.yaml --validate=false
